http://20.244.56.144/test/register

{
    "companyName": "goMart",
    "ownerName": "krati",
    "rollNo": "08",
    "ownerEmail": "210303105501@paruluniversity.ac.in",
    "accessCode": "QeYQhl"
}
